Integration update (#139)
* chore: bump versions for node, builder and base crates

<!-- ps-id: a472a40c-09b0-44e8-9f5f-1b7e2230453b -->

* chore: update cargo lock

<!-- ps-id: f6a914cd-b220-4223-8376-d32a1d570eca -->

* chore: update essential app utils manifest

<!-- ps-id: ef5c86a8-0ea9-4913-bbe7-e25b2a4da0c8 -->

* chore: update flake lock

<!-- ps-id: 9b3e7007-2d8b-45ea-8ba6-22b9c17bb987 -->

* update essential-rest-client builder_client.rs

<!-- ps-id: 7271bdad-ad72-484e-9d5d-cb3482c1c517 -->

* update essential-rest-client node_client.rs

<!-- ps-id: ae436064-f4b1-4baf-86dc-91e0b5a79d6c -->

* update apps utils builder.rs

<!-- ps-id: b22a9938-cb63-431e-bd57-904d00c967ff -->

* update apps utils deploy.rs

<!-- ps-id: 25296e68-3483-4854-8b21-1d717a95f802 -->

* update apps utils node.rs

<!-- ps-id: 0fe5c00f-e73a-424c-9248-66b9ce1392b4 -->

* update: apps transfer.rs

<!-- ps-id: 9d80eb46-5e4f-4d8a-b46e-e2f7efb3fd29 -->

* update: apps lib.rs

<!-- ps-id: a6a59115-ef86-4ab3-909c-5329494e8b93 -->

* update: apps test.rs

<!-- ps-id: f98cb830-5aae-49dc-9fbc-3140415e771e -->

* update: apps burn.rs

<!-- ps-id: 78e7af2a-5b70-404e-8418-da5490b2b175 -->

* update: apps mint.rs

<!-- ps-id: 81d86122-1188-4a30-a62d-1bb93ecc1eea -->

* fix: renaming in token contract

Renamed `TransferAuthMode::Signed(auth) => match auth.mode {`
to
`TransferAuthMode::Signed(a) => match a.mode {`
in order to fix compiler error:
```
pint build
   Compiling std [library] (path+root=df0ad451fc3c4baa)
   Compiling token [contract] (/home/furnic/Dev/essential/essential-integration/apps/token/pint/token)
Error: symbol `auth` has already been declared
     ╭─[/home/furnic/Dev/essential/essential-integration/apps/token/pint/token/src/contract.pnt:181:34]
     │
  96 │ predicate Mint(key: b256, amount: int, decimals: int, auth: MintAuth) {
     │                                                       ──┬─
     │                                                         ╰─── previous declaration of the symbol `auth` here
     │
 181 │         TransferAuthMode::Signed(auth) => match auth.mode {
     │                                  ──┬─
     │                                    ╰─── `auth` redeclared here
     │
     │ Note: `auth` must be declared or imported only once in this scope
─────╯
Error: `pintc` encountered an error: flattening error

```

<!-- ps-id: d108f397-b656-4dfb-9e80-3248b7e7eb3b -->

* chore: bump pint-submit version

* chore: bump pint-query version

* chore: bump pint-deploy version

* chore: bump essential-rest-client( version

* chore: update pint dependency versions

* chore: update flake.lock

* chore: bump version for app utils crate

* chore: update cargo manifest and lockfile

* test: fix tests

* update: support new Contract deserialization format

* update: pass SolutionSet to submit_solution fns

* update: fix pint deploy Contract deserialization

Changes needed for compatability with new pint release.

* temp: debug

* feat: Ensure programs are deployed alongside their contracts (#142)

* WIP: modify tests to use builder_client

* fix: update app-utils compile & deploy

* fix: use updated deployment

* fix: use updated deployment

* style: apply clippy suggestions

* chore: bump app versions

* refactor: rename and clean up fn deploy_contract()

* chore: update flake lock after bumping apps

* `pint-submit` and more docs fixes for compute graph and solution-set name changes in integration update (#144)

* fix: Update counter app and toml for SolutionSet naming changes

* fix: Change pint-submit to support SolutionSets. Update Deploy and Solve docs chapter.

* fix: More decision_variables ->  predicate_data docs fixes

* fix: Invalid exist command in front-end.sh, use exit

* ci: Temporarily disable the front-end.sh test to allow CI to pass and publish new versions of tools

* fix: Rm unused essential-debugger dep in app-utils

* fix: Run cargo fmt

---------

Co-authored-by: mitchmindtree <mitchell.nordine@essentialcontributions.com>