temp: renaming in token contract
Renamed `TransferAuthMode::Signed(auth) => match auth.mode {`
to
`TransferAuthMode::Signed(a) => match a.mode {`
in order to fix compiler error:
```
pint build
   Compiling std [library] (path+root=df0ad451fc3c4baa)
   Compiling token [contract] (/home/furnic/Dev/essential/essential-integration/apps/token/pint/token)
Error: symbol `auth` has already been declared
     ╭─[/home/furnic/Dev/essential/essential-integration/apps/token/pint/token/src/contract.pnt:181:34]
     │
  96 │ predicate Mint(key: b256, amount: int, decimals: int, auth: MintAuth) {
     │                                                       ──┬─
     │                                                         ╰─── previous declaration of the symbol `auth` here
     │
 181 │         TransferAuthMode::Signed(auth) => match auth.mode {
     │                                  ──┬─
     │                                    ╰─── `auth` redeclared here
     │
     │ Note: `auth` must be declared or imported only once in this scope
─────╯
Error: `pintc` encountered an error: flattening error

```

<!-- ps-id: d108f397-b656-4dfb-9e80-3248b7e7eb3b -->